### ISSUE TITLE
Critical Bug: Game Crashes/Save bricks if using speaker on train with only one stop

### ISSUE THREAD

**Issue by blazelink3** [PurpleCreate/Tramways#1]
**Describe the bug**
As title suggests, when using the Speaker on a train on a track featuring only one single stop, upon arriving at that station, the Speaker will deliver the line, and the game will promptly crash, and any attempt to reload that world will cause the same crash, bricking the save (presumably until a user goes into an NBT editor and manually deletes the train entity from the pertinent file). this error does not occur on a line with two stations (and thus presumably any non-one station line is entirely safe).

Crash Log:
[crash-2024-12-19_02.05.25-server.txt](https://github.com/user-attachments/files/18191413/crash-2024-12-19_02.05.25-server.txt)

given the cited error I would guess there may be some problem with trying to read some array of stations for whatever reason, and the idea that only 1 would exist not being properly accounted for as an edgecase, as the singular station would be registered at Index 0, leading it to attempt to read a nonexistent second station at index 1, which causes the crash

**To Reproduce**
build a train with a speaker, blaze burner/conductor on a track with only one singular station on it's length (my testing engine is shown below)
![2024-12-19_02 05 07](https://github.com/user-attachments/assets/cf119827-79e6-4f7b-9e5f-03515f07f1b0)

Create a schedule that assigns the sole station as the next stop, giving it to the conductor. once the train arrives, the Speaker will attempt to deliver it's line, sometimes succeeding and sometimes failing (this was in version 0.1.1 where I found the speaker would sometimes cut itself off, although I never found that happening in 0.1.0, although I dunno if that means it's an 0.1.1 specific bug), regardless of the circumstance, it will immediately crash upon "finishing" (or trying to). attempting to reload the world will result in the same crash again.

**Expected behavior**
It _should_ read out it's line and then stop, as there are no further stations to go to on this line. Obviously it should neither crash nor brick one's save.

**Technical Information:**
 - OS: Windows 10
 - Mod Loader: Forge (1.20.1-forge-47.3.0)
 - Mod Version: 0.1.1/0.1.0

**Additional context**
- Crash is repeated on both my full modlist, and a modlist stripped down to create 0.5.1-j, create Steam 'n' Rails 1.6.7 as well as Tramways 0.1.1.

- The test featuring two stations was a full circuit- I do not know if the bug would persist if the stations were on a straight section of line the test train moving back and forth along it's length.

**Comment by C1200** [comment]
Fixed in 9d1733a5
